title: Salawat Azeez
logo: /me.png
description: I am a detailed oriented and highly curious data analyst with three years of experience transforming complex data into insight. I have background in statistics, and a knowledge in comnputer science which enables me to bring both technical proficiency and business awarness to my work. I am highly proficient in using advanced Excel for report automation, SQL for data interrogation and manipulation and POWER BI for data visualization.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
